title: Testing new stuff
author: Liv3
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first git blog

# social links
github_username:  Liv3-Ver # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
